# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'WeatherCleanArchi' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WeatherCleanArchi
  
  pod 'SwiftGen', '5.3.0'
  pod 'Moya', '11.0.2'

  target 'WeatherCleanArchiTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
