name: Pull request

on: 
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  test:
    if: github.event.pull_request.draft == false
    runs-on: macos-10.15
    timeout-minutes: 30
    steps:
      - name: Git - Checkout
        uses: actions/checkout@v2.3.4
        with:
          ref: ${{ github.ref }}
      - name: Setup - Xcode
        run: sudo xcode-select -s /Applications/Xcode_11.2.1.app
      - name: Setup - Ruby and bundler dependencies
        uses: ruby/setup-ruby@v1.57.0
        with:
          ruby-version: 2.7.2
          bundler-cache: true
      - name: Test - Fastlane tests
        run: bundle exec fastlane test
